[user]
email = "4998544+hur@users.noreply.github.com"
name = "Atte Niemi"

[aliases]
b = ["branch"]
n = ["new"]

[template-aliases]
"format_timestamp(timestamp)" = "timestamp.ago()"

[ui]
default-command = "log"
